### ISSUE TITLE
Make logging work

### ISSUE THREAD

**Issue by pietrodn** [middleware2016/hadoop-accidents#2]
Log messages are currently lost, I didn't manage to correctly configure log4j.

**Comment by carduz** [comment]
Do you mean these? 
![schermata del 2017-01-15 02-21-45](https://cloud.githubusercontent.com/assets/10631614/21959510/644b48e4-dac9-11e6-971a-b37e0a7e6480.png)

**Comment by pietrodn** [comment]
Exactly. I'm glad they're showing on your machine, but I can't manage to make them appear on mine, neither on the console nor in the Hadoop logs (accessible with the web interface),

**Comment by pietrodn** [comment]
Ok, I found the logs, they're in `/usr/local/Cellar/hadoop/2.7.3/libexec/logs/userlogs` on OS X. @AlexDelbono this may be of interest also for you
